name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: jorelali/setup-elm@v2
        with:
          elm-version: 0.19.1
          
      - name: Install
        run: |
          yarn install
          
      - name: Test
        run: |
          yarn test

      - name: Build
        run: |
          yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
